### ISSUE TITLE
Keycloak realms not created during setup - Integrator Lab 4 impacted

### ISSUE THREAD

**Issue by nexus-Six** [RedHat-Middleware-Workshops/dayinthelife-integration#396]
When deploying the environment via RHPDS, the Keycloak realms are not created.  When clicking on the realm admin URL in Integrator Lab 4 guide there is a 404.  When logging into the Keycloak admin there is only the realm "master" available. So currently it is not possible to complete the Integrator Lab 4.

Current behavior : When clicking on the link [1] there is a 404

Expected behavior : When clicking on the link [1] the Keycloak realm login site of the current user should open

Steps to reproduce : Deploy the environment from RHPDS 

[1] https://github.com/RedHat-Middleware-Workshops/dayinthelife-integration/blob/96b39151053f3fa789161939d80bfb4ab68b7c03/docs/labs/citizen-integrator-track/lab04/walkthrough.adoc?plain=1#L35 

Thanks for looking into this.

**Comment by EricSaDev** [comment]
Hello @nexus-Six, 

my name is Eric Sá and i'm a Middleware Technical Account Manager at Red Hat.

Yesterday I had the same problem and opened a ticket for RHPDS General Support.

Today, they updated my request with the following comments:

"Hello Eric,
 
This is a bug that was discovered after you deployed and a patch has been pushed to fix it. Unfortunately, to fix this in situ it would require a re-run of the realm creation manually, but we don't have that in a playbook.
 
The only way to get past this is to deploy a new cluster."

I'll deploy a new cluster and test it.

Thanks
![DeepinScreenshot_select-area_20220131164459](https://user-images.githubusercontent.com/58058977/151861806-86cd3d21-2fb5-4bcd-aef6-a2b7e44ddcf6.png)
.

**Comment by hguerrero** [comment]
Thanks, @EricSaDev for the update on this issue. There was an issue with the Keycloak operator that lost the state after a pod restart. We updated the version of the Keycloak operator to the latest minor and that is fixed in production now. 

fixed by: https://github.com/redhat-cop/agnosticd/pull/4395
